export { default as Landing } from "./Landing";
export { default as About } from "./About";
export { default as Checkout } from "./Checkout";
export { default as Contact } from "./Contact";
export { default as Rooms } from "./Rooms";
export { default as Signin } from "./Signin";
export { default as AdminDashboard } from "./AdminDashboard";
export { default as AddRoom } from "./AddRoom";
export { default as UpdateRoom } from "./UpdateRoom";
